name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest -v

  build:
    needs: test  # Cette étape démarre après la réussite des tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-dockerhub-username/my-app:${{ github.sha }} .
          docker tag my-dockerhub-username/my-app:${{ github.sha }} my-dockerhub-username/my-app:latest

      - name: Push Docker image
        run: |
          docker push my-dockerhub-username/my-app:${{ github.sha }}
          docker push my-dockerhub-username/my-app:latest
